name: portfolio
description: My portfolio project.
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
     sdk: flutter
  jaspr: ^0.18.2
  jaspr_daisyui: ^0.1.0
  jaspr_flutter_embed: ^0.4.5
  jaspr_router: ^0.6.4
  logging: ^1.3.0
  web: ^1.1.0
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.1.1
  jaspr_builder: ^0.18.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jaspr_lints: ^0.3.1

jaspr:
  mode: static

flutter:
  uses-material-design: true

assets:
  - assets/icons/
  - assetes/images/
