name: portfolio
description: My portfolio project.
version: 0.0.1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  jaspr: ^0.20.0
  jaspr_content: ^0.3.0
  jaspr_lucide: ^0.4.2
  jaspr_router: ^0.7.0
  jaspr_tailwind: ^0.3.3
  jaspr_daisyui_components:
    path: ../jaspr_daisyui_components/
  logging: ^1.3.0
  web: ^1.1.0
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.5.4
  jaspr_builder: ^0.20.0
  json_serializable: ^6.9.5
  source_gen: ^2.0.0
  build_web_compilers: ^4.2.3

jaspr:
  mode: static

assets:
  - web/assets/icons/
  - web/assets/images/
